import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const branch = process.env.VSCODE_DOCS_BRANCH ?? 'main';
const tocUrl = `https://raw.githubusercontent.com/microsoft/vscode-docs/${branch}/learn/toc.json`;
const outputPath = path.join(process.cwd(), 'src', 'generated', 'learnCatalog.generated.ts');

const response = await fetch(tocUrl);
if (!response.ok) {
  throw new Error(`Failed to fetch ${tocUrl}: ${response.status} ${response.statusText}`);
}

const toc = await response.json();
if (!Array.isArray(toc)) {
  throw new Error('Expected learn/toc.json to be an array.');
}

const lessonIds = new Set();
const courses = toc.map((course, courseIndex) => {
  if (!course.name || !course.area || !Array.isArray(course.topics)) {
    throw new Error(`Invalid course entry at index ${courseIndex}.`);
  }

  return {
    id: course.area,
    title: course.name,
    description: course.description ?? '',
    area: course.area,
    order: courseIndex,
    lessons: course.topics.map((topic, lessonIndex) => {
      if (!Array.isArray(topic) || topic.length !== 2) {
        throw new Error(`Invalid topic in ${course.name} at index ${lessonIndex}.`);
      }

      const [title, learnPath] = topic;
      const prefix = `/learn/${course.area}/`;
      if (typeof title !== 'string' || typeof learnPath !== 'string' || !learnPath.startsWith(prefix)) {
        throw new Error(`Invalid topic path "${learnPath}" for ${course.name}.`);
      }

      const slug = learnPath.slice(prefix.length);
      const id = `${course.area}/${slug}`;
      if (lessonIds.has(id)) {
        throw new Error(`Duplicate lesson id ${id}.`);
      }
      lessonIds.add(id);

      return {
        id,
        courseId: course.area,
        title,
        area: course.area,
        slug,
        order: lessonIndex,
        sourcePath: `learn/${course.area}/${slug}.md`,
        canonicalUrl: `https://code.visualstudio.com${learnPath}`,
        rawMarkdownUrl: `https://raw.githubusercontent.com/microsoft/vscode-docs/${branch}/learn/${course.area}/${slug}.md`
      };
    })
  };
});

const generated = `// Generated by scripts/generateCatalog.mjs. Do not edit by hand.
import type { LearnCatalog } from '../catalog/types';

export const generatedLearnCatalog: LearnCatalog = ${JSON.stringify({
  source: {
    repository: 'microsoft/vscode-docs',
    branch,
    tocUrl,
    generatedAt: new Date().toISOString()
  },
  courses
}, null, 2)} as const;
`;

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(outputPath, generated, 'utf8');
console.log(`Generated ${outputPath} with ${courses.length} courses and ${lessonIds.size} lessons.`);
